"""Generate TESTING.md: every API test as a plain-English claim, grouped by
file and class. The docstrings ARE the catalog. A test without one fails
collection (see conftest.py), so this file can always be regenerated complete:

    python scripts/build_test_catalog.py
"""

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SUITE = "apps"
OUT = ROOT / "TESTING.md"

HEADER = """# API test catalog

Generated by `python scripts/build_test_catalog.py`. Regenerate after adding
tests; don't edit by hand. Each line is the behavior a test protects, taken
from its docstring (mandatory: collection fails without one).

Run the suite: `pytest` (check the exit code, never pipe it to tail).
"""


def first_paragraph(doc):
    if not doc:
        return ""
    return " ".join(doc.strip().split("\n\n")[0].split())


def main():
    items = []

    class Capture:
        def pytest_collection_finish(self, session):
            items.extend(session.items)

    rc = pytest.main(["--collect-only", "-q", SUITE, "-p", "no:cacheprovider"], plugins=[Capture()])
    if rc != 0 or not items:
        print(f"collection failed (exit {rc})")
        sys.exit(1)

    by_file = {}
    for item in items:
        path = Path(item.path).relative_to(ROOT).as_posix()
        cls = item.cls.__name__ if item.cls else ""
        cls_doc = first_paragraph(item.cls.__doc__) if item.cls else ""
        name = item.originalname or item.name
        by_file.setdefault(path, {}).setdefault((cls, cls_doc), {})[name] = first_paragraph(item.function.__doc__)

    lines = [HEADER]
    total = 0
    for path in sorted(by_file):
        groups = by_file[path]
        count = sum(len(tests) for tests in groups.values())
        total += count
        lines.append(f"\n## {path} ({count} tests)\n")
        for (cls, cls_doc), tests in groups.items():
            if cls:
                lines.append(f"\n### {cls}")
                if cls_doc:
                    lines.append(f"\n> {cls_doc}")
                lines.append("")
            for name, doc in tests.items():
                lines.append(f"- `{name}`: {doc}")
    lines.append(f"\n---\n\n{total} tests cataloged.\n")

    # LF everywhere, so CI's freshness check sees no difference between OSes.
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({total} tests)")


if __name__ == "__main__":
    main()
